# Generated by Django 4.0.4 on 2022-05-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_alter_expense_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Project',
            new_name='project',
        ),
    ]
